version: '3.8'
services:
  database:
    container_name: influxdb
    image: influx_image
    restart: always
    ports:
     - 8086:8086
    build: 
      context: .
      dockerfile: servicios/influx/Dockerfile

  broker:
    container_name: rabbit
    image: rabbit_image
    restart: always
    ports:
      - 1883:1883
      - 15672:15672
      - 5672:5672
    build: 
      context: .
      dockerfile: servicios/rabbit/Dockerfile    

  visualizador:
    container_name: grafana
    image: grafana_image
    restart: always
    ports:
      
      - 3000:3000
    build: 
      context: .
      dockerfile: servicios/grafana/Dockerfile  
  
  telegraf:
    image: telegraf:1.25.0
    container_name: telegraf
    restart: always
    environment:
      - INFLUX_TOKEN=MtGFPHZeEID7bJKxe7wWMl0L6iQH_KCK0glRzekMzmouwC_EIhUy9luiDchQ9r73m-Ea31sURFi7wpeCWoVZyg==
    command: --config http://influxdb:8086/api/v2/telegrafs/0ab008c4824d7000
    depends_on:
      - database
